workflows:
  ios-unsigned:
    name: Build gana777 iOS unsigned
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Instalando dependencias
        script: flutter pub get
      - name: Build iOS sin firma
        script: flutter build ios --release --no-codesign
      - name: Empaquetando .ipa
        script: |
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r gana777.ipa Payload
    artifacts:
      - build/ios/ipa/gana777.ipa
